// Code generated by protoc-gen-go.
// source: Command.proto
// DO NOT EDIT!

/*
Package boundless_services is a generated protocol buffer package.

It is generated from these files:
	Command.proto
	Event.proto
	worm.proto

It has these top-level messages:
	Command
*/
package boundless_services

import proto "github.com/golang/protobuf/proto"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal

type Command_ContextType int32

const (
	Command_DESKTOP Command_ContextType = 0
	Command_WEB     Command_ContextType = 1
	Command_MOBILE  Command_ContextType = 2
	Command_SERVICE Command_ContextType = 3
)

var Command_ContextType_name = map[int32]string{
	0: "DESKTOP",
	1: "WEB",
	2: "MOBILE",
	3: "SERVICE",
}
var Command_ContextType_value = map[string]int32{
	"DESKTOP": 0,
	"WEB":     1,
	"MOBILE":  2,
	"SERVICE": 3,
}

func (x Command_ContextType) String() string {
	return proto.EnumName(Command_ContextType_name, int32(x))
}

// Command from a client.
type Command struct {
	Id      string              `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Action  string              `protobuf:"bytes,2,opt,name=action" json:"action,omitempty"`
	Data    []byte              `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Context Command_ContextType `protobuf:"varint,4,opt,name=context,enum=boundless.services.Command_ContextType" json:"context,omitempty"`
}

func (m *Command) Reset()         { *m = Command{} }
func (m *Command) String() string { return proto.CompactTextString(m) }
func (*Command) ProtoMessage()    {}

func init() {
	proto.RegisterEnum("boundless.services.Command_ContextType", Command_ContextType_name, Command_ContextType_value)
}
