// Code generated by protoc-gen-go. DO NOT EDIT.
// source: Command.proto

/*
Package golang is a generated protocol buffer package.

It is generated from these files:
	Command.proto
	Event.proto
	worm.proto

It has these top-level messages:
	Command
	Event
	Response
	Subscription
*/
package golang

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Command_ContextType int32

const (
	Command_DESKTOP Command_ContextType = 0
	Command_WEB     Command_ContextType = 1
	Command_MOBILE  Command_ContextType = 2
	Command_SERVICE Command_ContextType = 3
)

var Command_ContextType_name = map[int32]string{
	0: "DESKTOP",
	1: "WEB",
	2: "MOBILE",
	3: "SERVICE",
}
var Command_ContextType_value = map[string]int32{
	"DESKTOP": 0,
	"WEB":     1,
	"MOBILE":  2,
	"SERVICE": 3,
}

func (x Command_ContextType) String() string {
	return proto.EnumName(Command_ContextType_name, int32(x))
}
func (Command_ContextType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

// Command from a client.
type Command struct {
	Id      string              `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Action  string              `protobuf:"bytes,2,opt,name=action" json:"action,omitempty"`
	Data    []byte              `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Context Command_ContextType `protobuf:"varint,4,opt,name=context,enum=Command_ContextType" json:"context,omitempty"`
}

func (m *Command) Reset()                    { *m = Command{} }
func (m *Command) String() string            { return proto.CompactTextString(m) }
func (*Command) ProtoMessage()               {}
func (*Command) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Command) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Command) GetAction() string {
	if m != nil {
		return m.Action
	}
	return ""
}

func (m *Command) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Command) GetContext() Command_ContextType {
	if m != nil {
		return m.Context
	}
	return Command_DESKTOP
}

func init() {
	proto.RegisterType((*Command)(nil), "Command")
	proto.RegisterEnum("Command_ContextType", Command_ContextType_name, Command_ContextType_value)
}

func init() { proto.RegisterFile("Command.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 193 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x75, 0xce, 0xcf, 0xcd,
	0x4d, 0xcc, 0x4b, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0xda, 0xcc, 0xc8, 0xc5, 0x0e, 0x15,
	0x11, 0xe2, 0xe3, 0x62, 0xca, 0x4c, 0x91, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x62, 0xca, 0x4c,
	0x11, 0x12, 0xe3, 0x62, 0x4b, 0x4c, 0x2e, 0xc9, 0xcc, 0xcf, 0x93, 0x60, 0x02, 0x8b, 0x41, 0x79,
	0x42, 0x42, 0x5c, 0x2c, 0x29, 0x89, 0x25, 0x89, 0x12, 0xcc, 0x0a, 0x8c, 0x1a, 0x3c, 0x41, 0x60,
	0xb6, 0x90, 0x1e, 0x17, 0x7b, 0x72, 0x7e, 0x5e, 0x49, 0x6a, 0x45, 0x89, 0x04, 0x8b, 0x02, 0xa3,
	0x06, 0x9f, 0x91, 0x88, 0x1e, 0xcc, 0x22, 0x67, 0x88, 0x78, 0x48, 0x65, 0x41, 0x6a, 0x10, 0x4c,
	0x91, 0x92, 0x0d, 0x17, 0x37, 0x92, 0xb8, 0x10, 0x37, 0x17, 0xbb, 0x8b, 0x6b, 0xb0, 0x77, 0x88,
	0x7f, 0x80, 0x00, 0x83, 0x10, 0x3b, 0x17, 0x73, 0xb8, 0xab, 0x93, 0x00, 0xa3, 0x10, 0x17, 0x17,
	0x9b, 0xaf, 0xbf, 0x93, 0xa7, 0x8f, 0xab, 0x00, 0x13, 0x48, 0x45, 0xb0, 0x6b, 0x50, 0x98, 0xa7,
	0xb3, 0xab, 0x00, 0xb3, 0x13, 0x47, 0x14, 0x5b, 0x7a, 0x7e, 0x4e, 0x62, 0x5e, 0x7a, 0x12, 0x1b,
	0xd8, 0x1b, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x66, 0x6e, 0x2b, 0xe6, 0xd7, 0x00, 0x00,
	0x00,
}
