// Code generated by protoc-gen-go.
// source: Event.proto
// DO NOT EDIT!

/*
Package boundless_services is a generated protocol buffer package.

It is generated from these files:
	Event.proto

It has these top-level messages:
	Event
*/
package boundless_services

import proto "github.com/golang/protobuf/proto"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal

// An event emitted
type Event struct {
	Id       string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Type     string `protobuf:"bytes,2,opt,name=type" json:"type,omitempty"`
	Data     []byte `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	ParentId string `protobuf:"bytes,4,opt,name=parentId" json:"parentId,omitempty"`
}

func (m *Event) Reset()         { *m = Event{} }
func (m *Event) String() string { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()    {}

func init() {
}
