// Code generated by protoc-gen-go. DO NOT EDIT.
// source: worm.proto

package golang

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Result of an rpc call
type Response struct {
	Success bool   `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
	Data    []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Code    int32  `protobuf:"varint,3,opt,name=code" json:"code,omitempty"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{0} }

func (m *Response) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *Response) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Response) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

// Subscribe for Events
type Subscription struct {
	Topic string `protobuf:"bytes,1,opt,name=topic" json:"topic,omitempty"`
}

func (m *Subscription) Reset()                    { *m = Subscription{} }
func (m *Subscription) String() string            { return proto.CompactTextString(m) }
func (*Subscription) ProtoMessage()               {}
func (*Subscription) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{1} }

func (m *Subscription) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

func init() {
	proto.RegisterType((*Response)(nil), "Response")
	proto.RegisterType((*Subscription)(nil), "Subscription")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for WormService service

type WormServiceClient interface {
	// Issue a Command
	IssueCommand(ctx context.Context, in *Command, opts ...grpc.CallOption) (*Response, error)
	// Subscribe, receive Events
	Subscribe(ctx context.Context, in *Subscription, opts ...grpc.CallOption) (WormService_SubscribeClient, error)
}

type wormServiceClient struct {
	cc *grpc.ClientConn
}

func NewWormServiceClient(cc *grpc.ClientConn) WormServiceClient {
	return &wormServiceClient{cc}
}

func (c *wormServiceClient) IssueCommand(ctx context.Context, in *Command, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/WormService/IssueCommand", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wormServiceClient) Subscribe(ctx context.Context, in *Subscription, opts ...grpc.CallOption) (WormService_SubscribeClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_WormService_serviceDesc.Streams[0], c.cc, "/WormService/Subscribe", opts...)
	if err != nil {
		return nil, err
	}
	x := &wormServiceSubscribeClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type WormService_SubscribeClient interface {
	Recv() (*Event, error)
	grpc.ClientStream
}

type wormServiceSubscribeClient struct {
	grpc.ClientStream
}

func (x *wormServiceSubscribeClient) Recv() (*Event, error) {
	m := new(Event)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for WormService service

type WormServiceServer interface {
	// Issue a Command
	IssueCommand(context.Context, *Command) (*Response, error)
	// Subscribe, receive Events
	Subscribe(*Subscription, WormService_SubscribeServer) error
}

func RegisterWormServiceServer(s *grpc.Server, srv WormServiceServer) {
	s.RegisterService(&_WormService_serviceDesc, srv)
}

func _WormService_IssueCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Command)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WormServiceServer).IssueCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/WormService/IssueCommand",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WormServiceServer).IssueCommand(ctx, req.(*Command))
	}
	return interceptor(ctx, in, info, handler)
}

func _WormService_Subscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Subscription)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(WormServiceServer).Subscribe(m, &wormServiceSubscribeServer{stream})
}

type WormService_SubscribeServer interface {
	Send(*Event) error
	grpc.ServerStream
}

type wormServiceSubscribeServer struct {
	grpc.ServerStream
}

func (x *wormServiceSubscribeServer) Send(m *Event) error {
	return x.ServerStream.SendMsg(m)
}

var _WormService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "WormService",
	HandlerType: (*WormServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IssueCommand",
			Handler:    _WormService_IssueCommand_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Subscribe",
			Handler:       _WormService_Subscribe_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "worm.proto",
}

func init() { proto.RegisterFile("worm.proto", fileDescriptor2) }

var fileDescriptor2 = []byte{
	// 219 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x8f, 0x31, 0x4b, 0xc4, 0x40,
	0x10, 0x85, 0x6f, 0xd5, 0x8b, 0xc9, 0x5c, 0xae, 0x19, 0x2c, 0x42, 0xaa, 0x10, 0x54, 0x52, 0x2d,
	0xa2, 0xff, 0x40, 0xb1, 0x10, 0xac, 0xf6, 0x0a, 0x41, 0x6c, 0x92, 0xcd, 0x70, 0x04, 0xcc, 0x4e,
	0xd8, 0xd9, 0x9c, 0x7f, 0x5f, 0xdc, 0x4b, 0xc0, 0xee, 0xfb, 0xa6, 0x78, 0xf3, 0x1e, 0xc0, 0x0f,
	0xfb, 0x51, 0x4f, 0x9e, 0x03, 0x97, 0xbb, 0xd7, 0x13, 0xb9, 0xb0, 0xc8, 0xfe, 0x85, 0xc7, 0xb1,
	0x75, 0xfd, 0x59, 0xeb, 0x77, 0x48, 0x0d, 0xc9, 0xc4, 0x4e, 0x08, 0x0b, 0xb8, 0x96, 0xd9, 0x5a,
	0x12, 0x29, 0x54, 0xa5, 0x9a, 0xd4, 0xac, 0x8a, 0x08, 0x57, 0x7d, 0x1b, 0xda, 0xe2, 0xa2, 0x52,
	0x4d, 0x6e, 0x22, 0xff, 0xdd, 0x2c, 0xf7, 0x54, 0x5c, 0x56, 0xaa, 0xd9, 0x9a, 0xc8, 0xf5, 0x2d,
	0xe4, 0x87, 0xb9, 0x13, 0xeb, 0x87, 0x29, 0x0c, 0xec, 0xf0, 0x06, 0xb6, 0x81, 0xa7, 0xc1, 0xc6,
	0xbc, 0xcc, 0x9c, 0xe5, 0xf1, 0x0b, 0x76, 0x1f, 0xec, 0xc7, 0x03, 0xf9, 0xd3, 0x60, 0x09, 0xef,
	0x20, 0x7f, 0x13, 0x99, 0x69, 0x29, 0x86, 0xa9, 0x5e, 0xa8, 0xcc, 0xf4, 0xda, 0xad, 0xde, 0xe0,
	0x3d, 0x64, 0x4b, 0x76, 0x47, 0xb8, 0xd7, 0xff, 0xff, 0x94, 0x89, 0x8e, 0x13, 0xeb, 0xcd, 0x83,
	0x7a, 0x4e, 0x3f, 0x93, 0x23, 0x7f, 0xb7, 0xee, 0xd8, 0x25, 0x71, 0xe2, 0xd3, 0x6f, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x15, 0x48, 0x56, 0x02, 0x0c, 0x01, 0x00, 0x00,
}
