// Code generated by protoc-gen-go.
// source: worm.proto
// DO NOT EDIT!

/*
Package boundless_services is a generated protocol buffer package.

It is generated from these files:
	worm.proto

It has these top-level messages:
	Command
	Response
*/
package boundless_services

import proto "github.com/golang/protobuf/proto"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal

type Command_ContextType int32

const (
	Command_DESKTOP Command_ContextType = 0
	Command_WEB     Command_ContextType = 1
	Command_ANDROID Command_ContextType = 2
	Command_IOS     Command_ContextType = 3
)

var Command_ContextType_name = map[int32]string{
	0: "DESKTOP",
	1: "WEB",
	2: "ANDROID",
	3: "IOS",
}
var Command_ContextType_value = map[string]int32{
	"DESKTOP": 0,
	"WEB":     1,
	"ANDROID": 2,
	"IOS":     3,
}

func (x Command_ContextType) String() string {
	return proto.EnumName(Command_ContextType_name, int32(x))
}

// The request command.
type Command struct {
	Action  string              `protobuf:"bytes,1,opt,name=action" json:"action,omitempty"`
	Data    []byte              `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Context Command_ContextType `protobuf:"varint,3,opt,name=context,enum=boundless.services.Command_ContextType" json:"context,omitempty"`
}

func (m *Command) Reset()         { *m = Command{} }
func (m *Command) String() string { return proto.CompactTextString(m) }
func (*Command) ProtoMessage()    {}

// The response from the service.
type Response struct {
	Message string `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}

func init() {
	proto.RegisterEnum("boundless.services.Command_ContextType", Command_ContextType_name, Command_ContextType_value)
}
