// Code generated by protoc-gen-go.
// source: Metadata.proto
// DO NOT EDIT!

/*
Package schema is a generated protocol buffer package.

It is generated from these files:
	Metadata.proto

It has these top-level messages:
	Metadata
*/
package schema

import proto "github.com/golang/protobuf/proto"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal

type Metadata struct {
	TracingTags map[string]string `protobuf:"bytes,1,rep,name=tracingTags" json:"tracingTags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *Metadata) Reset()         { *m = Metadata{} }
func (m *Metadata) String() string { return proto.CompactTextString(m) }
func (*Metadata) ProtoMessage()    {}

func (m *Metadata) GetTracingTags() map[string]string {
	if m != nil {
		return m.TracingTags
	}
	return nil
}

func init() {
}
