// Code generated by protoc-gen-go.
// source: boundlessgeo_schema/Command.proto
// DO NOT EDIT!

/*
Package schema is a generated protocol buffer package.

It is generated from these files:
	boundlessgeo_schema/Command.proto
	boundlessgeo_schema/Event.proto
	boundlessgeo_schema/Feature.proto
	boundlessgeo_schema/Metadata.proto
	boundlessgeo_schema/Msg.proto
	boundlessgeo_schema/worm.proto

It has these top-level messages:
	Command
*/
package schema

import proto "github.com/golang/protobuf/proto"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal

type Command_ContextType int32

const (
	Command_DESKTOP Command_ContextType = 0
	Command_WEB     Command_ContextType = 1
	Command_MOBILE  Command_ContextType = 2
	Command_SERVICE Command_ContextType = 3
)

var Command_ContextType_name = map[int32]string{
	0: "DESKTOP",
	1: "WEB",
	2: "MOBILE",
	3: "SERVICE",
}
var Command_ContextType_value = map[string]int32{
	"DESKTOP": 0,
	"WEB":     1,
	"MOBILE":  2,
	"SERVICE": 3,
}

func (x Command_ContextType) String() string {
	return proto.EnumName(Command_ContextType_name, int32(x))
}

// Command from a client.
type Command struct {
	Id       string              `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Action   string              `protobuf:"bytes,2,opt,name=action" json:"action,omitempty"`
	Data     []byte              `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Context  Command_ContextType `protobuf:"varint,4,opt,name=context,enum=Command_ContextType" json:"context,omitempty"`
	Metadata *Metadata           `protobuf:"bytes,5,opt,name=metadata" json:"metadata,omitempty"`
	Created  int64               `protobuf:"varint,6,opt,name=created" json:"created,omitempty"`
}

func (m *Command) Reset()         { *m = Command{} }
func (m *Command) String() string { return proto.CompactTextString(m) }
func (*Command) ProtoMessage()    {}

func (m *Command) GetMetadata() *Metadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func init() {
	proto.RegisterEnum("Command_ContextType", Command_ContextType_name, Command_ContextType_value)
}
