// Code generated by protoc-gen-go.
// source: boundlessgeo_schema/Event.proto
// DO NOT EDIT!

package schema

import proto "github.com/golang/protobuf/proto"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal

// An event emitted
type Event struct {
	Id       string    `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Type     string    `protobuf:"bytes,2,opt,name=type" json:"type,omitempty"`
	Data     []byte    `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	ParentId string    `protobuf:"bytes,4,opt,name=parentId" json:"parentId,omitempty"`
	Metadata *Metadata `protobuf:"bytes,5,opt,name=metadata" json:"metadata,omitempty"`
	Created  int64     `protobuf:"varint,6,opt,name=created" json:"created,omitempty"`
}

func (m *Event) Reset()         { *m = Event{} }
func (m *Event) String() string { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()    {}

func (m *Event) GetMetadata() *Metadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func init() {
}
