// Code generated by protoc-gen-go.
// source: boundlessgeo_schema/Feature.proto
// DO NOT EDIT!

package schema

import proto "github.com/golang/protobuf/proto"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal

type OperationType int32

const (
	OperationType_INSERT OperationType = 0
	OperationType_UPDATE OperationType = 1
	OperationType_DELETE OperationType = 2
)

var OperationType_name = map[int32]string{
	0: "INSERT",
	1: "UPDATE",
	2: "DELETE",
}
var OperationType_value = map[string]int32{
	"INSERT": 0,
	"UPDATE": 1,
	"DELETE": 2,
}

func (x OperationType) String() string {
	return proto.EnumName(OperationType_name, int32(x))
}

type Feature struct {
	Fid        string            `protobuf:"bytes,1,opt,name=fid" json:"fid,omitempty"`
	Properties map[string]string `protobuf:"bytes,2,rep,name=properties" json:"properties,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Geometry   []byte            `protobuf:"bytes,3,opt,name=geometry,proto3" json:"geometry,omitempty"`
}

func (m *Feature) Reset()         { *m = Feature{} }
func (m *Feature) String() string { return proto.CompactTextString(m) }
func (*Feature) ProtoMessage()    {}

func (m *Feature) GetProperties() map[string]string {
	if m != nil {
		return m.Properties
	}
	return nil
}

type Operation struct {
	Operation OperationType `protobuf:"varint,1,opt,name=operation,enum=OperationType" json:"operation,omitempty"`
	Source    string        `protobuf:"bytes,2,opt,name=source" json:"source,omitempty"`
	Feature   *Feature      `protobuf:"bytes,3,opt,name=feature" json:"feature,omitempty"`
}

func (m *Operation) Reset()         { *m = Operation{} }
func (m *Operation) String() string { return proto.CompactTextString(m) }
func (*Operation) ProtoMessage()    {}

func (m *Operation) GetFeature() *Feature {
	if m != nil {
		return m.Feature
	}
	return nil
}

func init() {
	proto.RegisterEnum("OperationType", OperationType_name, OperationType_value)
}
