// Code generated by protoc-gen-go. DO NOT EDIT.
// source: boundlessgeo_schema/Feature.proto

package schema

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type OperationType int32

const (
	OperationType_INSERT OperationType = 0
	OperationType_UPDATE OperationType = 1
	OperationType_DELETE OperationType = 2
)

var OperationType_name = map[int32]string{
	0: "INSERT",
	1: "UPDATE",
	2: "DELETE",
}
var OperationType_value = map[string]int32{
	"INSERT": 0,
	"UPDATE": 1,
	"DELETE": 2,
}

func (x OperationType) String() string {
	return proto.EnumName(OperationType_name, int32(x))
}
func (OperationType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_Feature_535d9abfe516bbdb, []int{0}
}

type Feature struct {
	Fid                  string            `protobuf:"bytes,1,opt,name=fid" json:"fid,omitempty"`
	Properties           map[string]string `protobuf:"bytes,2,rep,name=properties" json:"properties,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Geometry             []byte            `protobuf:"bytes,3,opt,name=geometry,proto3" json:"geometry,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Feature) Reset()         { *m = Feature{} }
func (m *Feature) String() string { return proto.CompactTextString(m) }
func (*Feature) ProtoMessage()    {}
func (*Feature) Descriptor() ([]byte, []int) {
	return fileDescriptor_Feature_535d9abfe516bbdb, []int{0}
}
func (m *Feature) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Feature.Unmarshal(m, b)
}
func (m *Feature) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Feature.Marshal(b, m, deterministic)
}
func (dst *Feature) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Feature.Merge(dst, src)
}
func (m *Feature) XXX_Size() int {
	return xxx_messageInfo_Feature.Size(m)
}
func (m *Feature) XXX_DiscardUnknown() {
	xxx_messageInfo_Feature.DiscardUnknown(m)
}

var xxx_messageInfo_Feature proto.InternalMessageInfo

func (m *Feature) GetFid() string {
	if m != nil {
		return m.Fid
	}
	return ""
}

func (m *Feature) GetProperties() map[string]string {
	if m != nil {
		return m.Properties
	}
	return nil
}

func (m *Feature) GetGeometry() []byte {
	if m != nil {
		return m.Geometry
	}
	return nil
}

type Operation struct {
	Operation            OperationType `protobuf:"varint,1,opt,name=operation,enum=OperationType" json:"operation,omitempty"`
	Source               string        `protobuf:"bytes,2,opt,name=source" json:"source,omitempty"`
	Feature              *Feature      `protobuf:"bytes,3,opt,name=feature" json:"feature,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Operation) Reset()         { *m = Operation{} }
func (m *Operation) String() string { return proto.CompactTextString(m) }
func (*Operation) ProtoMessage()    {}
func (*Operation) Descriptor() ([]byte, []int) {
	return fileDescriptor_Feature_535d9abfe516bbdb, []int{1}
}
func (m *Operation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Operation.Unmarshal(m, b)
}
func (m *Operation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Operation.Marshal(b, m, deterministic)
}
func (dst *Operation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Operation.Merge(dst, src)
}
func (m *Operation) XXX_Size() int {
	return xxx_messageInfo_Operation.Size(m)
}
func (m *Operation) XXX_DiscardUnknown() {
	xxx_messageInfo_Operation.DiscardUnknown(m)
}

var xxx_messageInfo_Operation proto.InternalMessageInfo

func (m *Operation) GetOperation() OperationType {
	if m != nil {
		return m.Operation
	}
	return OperationType_INSERT
}

func (m *Operation) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *Operation) GetFeature() *Feature {
	if m != nil {
		return m.Feature
	}
	return nil
}

func init() {
	proto.RegisterType((*Feature)(nil), "Feature")
	proto.RegisterMapType((map[string]string)(nil), "Feature.PropertiesEntry")
	proto.RegisterType((*Operation)(nil), "Operation")
	proto.RegisterEnum("OperationType", OperationType_name, OperationType_value)
}

func init() {
	proto.RegisterFile("boundlessgeo_schema/Feature.proto", fileDescriptor_Feature_535d9abfe516bbdb)
}

var fileDescriptor_Feature_535d9abfe516bbdb = []byte{
	// 299 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x51, 0x4d, 0x4b, 0xc3, 0x40,
	0x14, 0x74, 0x53, 0x4c, 0xdb, 0x57, 0xad, 0x61, 0x11, 0x0d, 0x3d, 0xd5, 0x9e, 0x8a, 0x68, 0x84,
	0xf6, 0x52, 0x04, 0x0f, 0x96, 0xae, 0x20, 0x88, 0x96, 0x35, 0x5e, 0xbc, 0x48, 0x9a, 0xbe, 0xd4,
	0xd0, 0x26, 0x1b, 0x36, 0x1b, 0x21, 0xff, 0xca, 0x9f, 0x28, 0xf9, 0xd8, 0x58, 0xbd, 0xbd, 0x99,
	0xd9, 0x37, 0xb3, 0x8f, 0x81, 0x8b, 0x95, 0xc8, 0xe2, 0xf5, 0x0e, 0xd3, 0x74, 0x83, 0xe2, 0x23,
	0xf5, 0x3f, 0x31, 0xf2, 0x6e, 0x1e, 0xd0, 0x53, 0x99, 0x44, 0x27, 0x91, 0x42, 0x89, 0xd1, 0x37,
	0x81, 0x76, 0xcd, 0x50, 0x0b, 0x5a, 0x41, 0xb8, 0xb6, 0xc9, 0x90, 0x8c, 0xbb, 0xbc, 0x18, 0xe9,
	0x0c, 0x20, 0x91, 0x22, 0x41, 0xa9, 0x42, 0x4c, 0x6d, 0x63, 0xd8, 0x1a, 0xf7, 0x26, 0xb6, 0xa3,
	0x1d, 0x96, 0x8d, 0xc4, 0x62, 0x25, 0x73, 0xbe, 0xf7, 0x96, 0x0e, 0xa0, 0xb3, 0x41, 0x11, 0xa1,
	0x92, 0xb9, 0xdd, 0x1a, 0x92, 0xf1, 0x11, 0x6f, 0xf0, 0xe0, 0x0e, 0x4e, 0xfe, 0xad, 0x16, 0xd1,
	0x5b, 0xcc, 0x75, 0xf4, 0x16, 0x73, 0x7a, 0x0a, 0x87, 0x5f, 0xde, 0x2e, 0x43, 0xdb, 0x28, 0xb9,
	0x0a, 0xdc, 0x1a, 0x33, 0x32, 0xca, 0xa0, 0xfb, 0x92, 0xa0, 0xf4, 0x54, 0x28, 0x62, 0x7a, 0x05,
	0x5d, 0xa1, 0x41, 0xb9, 0xde, 0x9f, 0xf4, 0x9d, 0x46, 0x76, 0xf3, 0x04, 0xf9, 0xef, 0x03, 0x7a,
	0x06, 0x66, 0x2a, 0x32, 0xe9, 0x6b, 0xd7, 0x1a, 0xd1, 0x11, 0xb4, 0x83, 0xea, 0xa8, 0xf2, 0xb3,
	0xbd, 0x49, 0x47, 0x1f, 0xc9, 0xb5, 0x70, 0x39, 0x85, 0xe3, 0x3f, 0xbe, 0x14, 0xc0, 0x7c, 0x7c,
	0x7e, 0x65, 0xdc, 0xb5, 0x0e, 0x8a, 0xf9, 0x6d, 0xb9, 0xb8, 0x77, 0x99, 0x45, 0x8a, 0x79, 0xc1,
	0x9e, 0x98, 0xcb, 0x2c, 0x63, 0x7e, 0x0d, 0xe7, 0xbe, 0x88, 0x9c, 0xfd, 0x1e, 0x9c, 0xaa, 0x87,
	0x39, 0xd4, 0x09, 0xcb, 0x55, 0xf0, 0x6e, 0x56, 0xdc, 0xca, 0x2c, 0x4b, 0x99, 0xfe, 0x04, 0x00,
	0x00, 0xff, 0xff, 0x83, 0x44, 0x69, 0x15, 0xb9, 0x01, 0x00, 0x00,
}
