// Code generated by protoc-gen-go. DO NOT EDIT.
// source: boundlessgeo_schema/worm.proto

/*
Package schema is a generated protocol buffer package.

It is generated from these files:
	boundlessgeo_schema/worm.proto
	boundlessgeo_schema/Command.proto
	boundlessgeo_schema/Event.proto
	boundlessgeo_schema/Metadata.proto

It has these top-level messages:
	Response
	Subscription
	Command
	Event
	Metadata
*/
package schema

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Result of an rpc call
type Response struct {
	Success bool   `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
	Data    []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Code    int32  `protobuf:"varint,3,opt,name=code" json:"code,omitempty"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Response) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *Response) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Response) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

// Subscribe for Events
type Subscription struct {
	Topic string `protobuf:"bytes,1,opt,name=topic" json:"topic,omitempty"`
}

func (m *Subscription) Reset()                    { *m = Subscription{} }
func (m *Subscription) String() string            { return proto.CompactTextString(m) }
func (*Subscription) ProtoMessage()               {}
func (*Subscription) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Subscription) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

func init() {
	proto.RegisterType((*Response)(nil), "Response")
	proto.RegisterType((*Subscription)(nil), "Subscription")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for WormService service

type WormServiceClient interface {
	// Issue a Command
	IssueCommand(ctx context.Context, in *Command, opts ...grpc.CallOption) (*Response, error)
	// Subscribe, receive Events
	Subscribe(ctx context.Context, in *Subscription, opts ...grpc.CallOption) (WormService_SubscribeClient, error)
}

type wormServiceClient struct {
	cc *grpc.ClientConn
}

func NewWormServiceClient(cc *grpc.ClientConn) WormServiceClient {
	return &wormServiceClient{cc}
}

func (c *wormServiceClient) IssueCommand(ctx context.Context, in *Command, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/WormService/IssueCommand", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wormServiceClient) Subscribe(ctx context.Context, in *Subscription, opts ...grpc.CallOption) (WormService_SubscribeClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_WormService_serviceDesc.Streams[0], c.cc, "/WormService/Subscribe", opts...)
	if err != nil {
		return nil, err
	}
	x := &wormServiceSubscribeClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type WormService_SubscribeClient interface {
	Recv() (*Event, error)
	grpc.ClientStream
}

type wormServiceSubscribeClient struct {
	grpc.ClientStream
}

func (x *wormServiceSubscribeClient) Recv() (*Event, error) {
	m := new(Event)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for WormService service

type WormServiceServer interface {
	// Issue a Command
	IssueCommand(context.Context, *Command) (*Response, error)
	// Subscribe, receive Events
	Subscribe(*Subscription, WormService_SubscribeServer) error
}

func RegisterWormServiceServer(s *grpc.Server, srv WormServiceServer) {
	s.RegisterService(&_WormService_serviceDesc, srv)
}

func _WormService_IssueCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Command)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WormServiceServer).IssueCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/WormService/IssueCommand",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WormServiceServer).IssueCommand(ctx, req.(*Command))
	}
	return interceptor(ctx, in, info, handler)
}

func _WormService_Subscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Subscription)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(WormServiceServer).Subscribe(m, &wormServiceSubscribeServer{stream})
}

type WormService_SubscribeServer interface {
	Send(*Event) error
	grpc.ServerStream
}

type wormServiceSubscribeServer struct {
	grpc.ServerStream
}

func (x *wormServiceSubscribeServer) Send(m *Event) error {
	return x.ServerStream.SendMsg(m)
}

var _WormService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "WormService",
	HandlerType: (*WormServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IssueCommand",
			Handler:    _WormService_IssueCommand_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Subscribe",
			Handler:       _WormService_Subscribe_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "boundlessgeo_schema/worm.proto",
}

func init() { proto.RegisterFile("boundlessgeo_schema/worm.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 240 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x8f, 0x41, 0x4b, 0xfc, 0x30,
	0x10, 0xc5, 0x37, 0xff, 0xbf, 0x5b, 0xdb, 0xb1, 0x5e, 0x82, 0x87, 0xd2, 0x83, 0xd6, 0xa2, 0xd2,
	0x53, 0x14, 0xfd, 0x06, 0x8a, 0x07, 0xc1, 0x53, 0xf6, 0x20, 0x88, 0x20, 0x6d, 0x3a, 0x68, 0xc1,
	0x64, 0x4a, 0x26, 0x5d, 0xbf, 0xbe, 0x98, 0x76, 0xc1, 0xc3, 0xde, 0xde, 0x4b, 0x1e, 0x6f, 0xde,
	0x0f, 0x4e, 0x3b, 0x9a, 0x5c, 0xff, 0x85, 0xcc, 0x1f, 0x48, 0xef, 0x6c, 0x3e, 0xd1, 0xb6, 0xd7,
	0xdf, 0xe4, 0xad, 0x1a, 0x3d, 0x05, 0x2a, 0xcf, 0xf6, 0xfd, 0x3f, 0x6e, 0xd1, 0x85, 0x25, 0x70,
	0xbe, 0x2f, 0xf0, 0x40, 0xd6, 0xb6, 0xae, 0x9f, 0x23, 0xf5, 0x33, 0xa4, 0x1a, 0x79, 0x24, 0xc7,
	0x28, 0x0b, 0x38, 0xe4, 0xc9, 0x18, 0x64, 0x2e, 0x44, 0x25, 0x9a, 0x54, 0xef, 0xac, 0x94, 0x70,
	0xd0, 0xb7, 0xa1, 0x2d, 0xfe, 0x55, 0xa2, 0xc9, 0x75, 0xd4, 0xbf, 0x6f, 0x86, 0x7a, 0x2c, 0xfe,
	0x57, 0xa2, 0x59, 0xeb, 0xa8, 0xeb, 0x0b, 0xc8, 0x37, 0x53, 0xc7, 0xc6, 0x0f, 0x63, 0x18, 0xc8,
	0xc9, 0x13, 0x58, 0x07, 0x1a, 0x07, 0x13, 0xfb, 0x32, 0x3d, 0x9b, 0xdb, 0x37, 0x38, 0x7a, 0x21,
	0x6f, 0x37, 0xe8, 0xb7, 0x83, 0x41, 0x79, 0x09, 0xf9, 0x13, 0xf3, 0x84, 0xcb, 0x30, 0x99, 0xaa,
	0x45, 0x95, 0x99, 0xda, 0x6d, 0xab, 0x57, 0xf2, 0x0a, 0xb2, 0xa5, 0xbb, 0x43, 0x79, 0xac, 0xfe,
	0xde, 0x29, 0x13, 0x15, 0xb1, 0xeb, 0xd5, 0x8d, 0xb8, 0x4f, 0x5f, 0x93, 0x99, 0xb4, 0x4b, 0x22,
	0xe2, 0xdd, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x5a, 0xc7, 0xc3, 0x8c, 0x48, 0x01, 0x00, 0x00,
}
